// Canonical preset projection. No network access or build-time sibling checkout required.
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const catalog = JSON.parse(readFileSync(join(root, 'presets.json'), 'utf8'));
const presets = catalog.presets;
assert.equal(catalog.version, 1);
assert.equal(new Set(presets.map(p => p.id)).size, presets.length, 'duplicate preset IDs');
for (const p of presets) {
    for (const key of ['id', 'label', 'description', 'example']) assert.ok(typeof p[key] === 'string' && p[key], `${p.id}: ${key}`);
    assert.ok(['text', 'link'].includes(p.match));
    assert.equal(typeof p.preview, 'boolean');
    if (p.extensions) {
        assert.ok(p.extensions.every(e => /^[a-z0-9]+$/.test(e)));
        assert.ok(p.extensions.includes(p.example.split('.').at(-1)), `${p.id}: extension example`);
    }
}
const resolved = presets.map(p => {
    let pattern = p.pattern ?? '';
    let name = p.label;
    if (p.integration) {
        const manifest = JSON.parse(readFileSync(join(root, 'integrations', `${p.integration}.json`), 'utf8'));
        const matches = manifest.matchers.filter(m => (m.kind ?? 'link') === p.match && new RegExp(m.pattern).test(p.example));
        assert.equal(matches.length, 1, `${p.id}: exactly one matcher must claim example`);
        pattern = matches[0].pattern;
        name = `${manifest.name}: ${matches[0].description || p.label}`;
    }
    return { ...p, name, pattern };
});
const wide = s => 'L' + JSON.stringify(s);
const list = a => '{ ' + (a ?? []).map(wide).join(', ') + ' }';
const group = s => ({none:'None',sourceCode:'SourceCode'}[s] ?? s[0].toUpperCase()+s.slice(1));
const header = `// Generated by Lintel conformance/sync-presets.mjs. Do not edit.\n` +
`inline std::span<const LinkTooltipPreset> GetLinkTooltipPresets() noexcept\n{\n    static const LinkTooltipPreset presets[] = {\n` +
resolved.map(p => `        { ${wide(p.id)}, ${wide(p.name)}, ${wide(p.description)}, Model::HyperlinkMatchKind::${p.match === 'text' ? 'Text' : 'Link'}, ${list(p.schemes)}, ${wide(p.pattern)}, Model::HyperlinkFileTypeGroup::${group(p.fileTypeGroup ?? 'none')}, ${list(p.extensions)}, ${wide(p.integration)}, ${p.preview}, ${list(p.legacyNames)} },`).join('\n') +
`\n    };\n    return presets;\n}\n\ninline std::wstring_view GetLinkTooltipPresetSample(std::wstring_view id) noexcept\n{\n` +
resolved.map(p => `    if (id == ${wide(p.id)}) return ${wide(p.sample ?? p.example)};`).join('\n') + '\n    return {};\n}\n';
const ts = '// Generated by Lintel conformance/sync-presets.mjs. Do not edit.\nexport const presetCatalog = ' + JSON.stringify(presets, null, 4) + ' as const\n';
const args = process.argv.slice(2);
const check = args.includes('--check');
function target(flag, relative, content) {
    const index = args.indexOf(flag);
    if (index < 0) return;
    assert.ok(args[index+1], `missing path for ${flag}`);
    const path = join(args[index+1], relative);
    if (check) assert.equal(readFileSync(path, 'utf8').replace(/\r\n/g,'\n'), content, `${path}: stale generated catalog`);
    else writeFileSync(path, content);
    console.log(`${check ? 'Checked' : 'Synced'} ${path}`);
}
target('--terminal', 'src/cascadia/TerminalSettingsEditor/LinkTooltipPresets.g.h', header);
target('--torbie', 'tabby-links/src/presets.generated.ts', ts);
console.log(`Validated ${presets.length} canonical presets.`);
